// Main client
export { RunicsClient } from "./client.js";

// MCP server factory
export { createRunicsMcpServer } from "./mcp.js";
export type { McpServerOptions } from "./mcp.js";

// Types
export type {
	CompositionPart,
	CompositionResult,
	FeedbackParams,
	FindSkillOptions,
	FindSkillResponse,
	GenerationHints,
	ListSkillsOptions,
	PaginatedSkillList,
	RunicsClientOptions,
	SearchMeta,
	SearchTrace,
	Skill,
	SkillResult,
	// v4 types
	CompositionStep,
	ForkInput,
	CopyInput,
	ExtendInput,
	CompositionInput,
	ForkResult,
	CompositionDetail,
	AncestryNode,
	ForkNode,
	DependentNode,
	InvocationBatch,
	CoOccurrenceResult,
	StarStatus,
	LeaderboardEntry,
	LeaderboardResponse,
	AuthorProfile,
	AuthorSkillsResponse,
	PublishSkillInput,
	UpdateSkillInput,
	// v5 types
	IndexSkillInput,
	IndexSkillResult,
	DeleteSkillResult,
	UploadBundleResult,
	TierDistribution,
	MatchSourceStats,
	LatencyPercentiles,
	CostBreakdown,
	FailedQuery,
	Tier3Pattern,
	EvalRunResult,
	EvalResult,
	AdminScanResult,
	AdminBackfillResult,
	// v5.2 types
	StatusChangeInput,
	SkillVersion,
	SkillVersionsResponse,
	EvalRunSummary,
	EvalListResponse,
	RevokedImpactResponse,
	VulnerableUsageResponse,
} from "./types.js";

// Zod schemas (for consumers who want to extend validation)
export {
	CompositionPartSchema,
	CompositionResultSchema,
	FindSkillResponseSchema,
	GenerationHintsSchema,
	PaginatedSkillListSchema,
	SearchMetaSchema,
	SearchTraceSchema,
	SkillResultSchema,
	SkillSchema,
	// v4 schemas
	CompositionStepSchema,
	ForkInputSchema,
	CopyInputSchema,
	ExtendInputSchema,
	CompositionInputSchema,
	ForkResultSchema,
	CompositionDetailSchema,
	AncestryNodeSchema,
	ForkNodeSchema,
	DependentNodeSchema,
	InvocationBatchSchema,
	CoOccurrenceResultSchema,
	StarStatusSchema,
	LeaderboardEntrySchema,
	LeaderboardResponseSchema,
	AuthorProfileSchema,
	AuthorSkillsResponseSchema,
	PublishSkillInputSchema,
	UpdateSkillInputSchema,
	// v5 schemas
	IndexSkillInputSchema,
	IndexSkillResultSchema,
	DeleteSkillResultSchema,
	UploadBundleResultSchema,
	TierDistributionSchema,
	MatchSourceStatsSchema,
	LatencyPercentilesSchema,
	CostBreakdownSchema,
	FailedQuerySchema,
	Tier3PatternSchema,
	EvalRunResultSchema,
	EvalResultSchema,
	AdminScanResultSchema,
	AdminBackfillResultSchema,
	// v5.2 schemas
	StatusChangeInputSchema,
	SkillVersionSchema,
	SkillVersionsResponseSchema,
	EvalRunSummarySchema,
	EvalListResponseSchema,
	RevokedImpactResponseSchema,
	VulnerableUsageResponseSchema,
} from "./schemas.js";

// Errors
export {
	RunicsError,
	RunicsNetworkError,
	RunicsNotFoundError,
	RunicsRateLimitError,
	RunicsServerError,
	RunicsValidationError,
} from "./errors.js";
